<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: EmptyResponse.proto

namespace GPBMetadata;

class EmptyResponse
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0a430a13456d707479526573706f6e73652e70726f746f12134150494761" .
            "74657761792e70726f746f627566220f0a0d456d707479526573706f6e73" .
            "65620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

