<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Request.proto

namespace GPBMetadata;

class Request
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Google\Protobuf\Any::initOnce();
        \GPBMetadata\RequestType::initOnce();
        $pool->internalAddGeneratedFile(hex2bin(
            "0ae0010a0d526571756573742e70726f746f121341504947617465776179" .
            "2e70726f746f6275661a1152657175657374547970652e70726f746f229e" .
            "010a0752657175657374120d0a056170706964180120012809120e0a0661" .
            "6374696f6e180220012809120c0a047369676e180320012809120c0a0475" .
            "756964180420012809122e0a047479706518052001280e32202e41504947" .
            "6174657761792e70726f746f6275662e526571756573745479706512220a" .
            "0464617461180f2001280b32142e676f6f676c652e70726f746f6275662e" .
            "416e794a040806100f620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

