<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: RequestType.proto

namespace GPBMetadata;

class RequestType
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0a540a1152657175657374547970652e70726f746f121341504947617465" .
            "7761792e70726f746f6275662a220a0b526571756573745479706512080a" .
            "0453594e43100012090a054153594e431001620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

