<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Request.proto

namespace GPBMetadata;

class Request
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Google\Protobuf\Any::initOnce();
        $pool->internalAddGeneratedFile(hex2bin(
            "0aeb010a0d526571756573742e70726f746f121341504947617465776179" .
            "2e70726f746f62756622bc010a0752657175657374120d0a056170706964" .
            "180120012809120e0a06616374696f6e180220012809120c0a047369676e" .
            "180320012809120c0a0475756964180420012809122f0a04747970651805" .
            "2001280e32212e415049476174657761792e70726f746f6275662e526571" .
            "756573742e5479706512220a0464617461180f2001280b32142e676f6f67" .
            "6c652e70726f746f6275662e416e79221b0a045479706512080a0453594e" .
            "43100012090a054153594e4310014a040806100f620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

