<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ResponseCode.proto

namespace GPBMetadata;

class ResponseCode
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0aab010a12526573706f6e7365436f64652e70726f746f12134150494761" .
            "74657761792e70726f746f6275662a780a0c526573706f6e7365436f6465" .
            "120b0a0753554343455353100012110a0d57524f4e475f52455155455354" .
            "100112100a0c494e56414c49445f41555448100212120a0e494e56414c49" .
            "445f414354494f4e100312170a13534552564943455f554e524541434841" .
            "424c45100412090a054f544845521005620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

