<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Response.proto

namespace GPBMetadata;

class Response
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Google\Protobuf\Any::initOnce();
        $pool->internalAddGeneratedFile(hex2bin(
            "0aab020a0e526573706f6e73652e70726f746f1213415049476174657761" .
            "792e70726f746f62756622fb010a08526573706f6e736512300a04636f64" .
            "6518022001280e32222e415049476174657761792e70726f746f6275662e" .
            "526573706f6e73652e436f6465120c0a0475756964180320012809120d0a" .
            "056572726f7218042001280912220a0464617461180f2001280b32142e67" .
            "6f6f676c652e70726f746f6275662e416e7922700a04436f6465120b0a07" .
            "53554343455353100012110a0d57524f4e475f5245515545535410011210" .
            "0a0c494e56414c49445f41555448100212120a0e494e56414c49445f4143" .
            "54494f4e100312170a13534552564943455f554e524541434841424c4510" .
            "0412090a054f5448455210054a04080110024a040805100f620670726f74" .
            "6f33"
        ));

        static::$is_initialized = true;
    }
}

