<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: EmptyResponse.proto

namespace APIGateway\Protobuf;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>APIGateway.protobuf.EmptyResponse</code>
 */
class EmptyResponse extends \Google\Protobuf\Internal\Message
{

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\EmptyResponse::initOnce();
        parent::__construct($data);
    }

}

