<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Request.proto

namespace APIGateway\Protobuf;

if (false) {
    /**
     * This class is deprecated. Use APIGateway\Protobuf\Request\Type instead.
     * @deprecated
     */
    class Request_Type {}
}
class_exists(Request\Type::class);
@trigger_error('APIGateway\Protobuf\Request_Type is deprecated and will be removed in the next major release. Use APIGateway\Protobuf\Request\Type instead', E_USER_DEPRECATED);

