<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: RequestType.proto

namespace APIGateway\Protobuf;

/**
 * Protobuf type <code>APIGateway.protobuf.RequestType</code>
 */
class RequestType
{
    /**
     * Generated from protobuf enum <code>SYNC = 0;</code>
     */
    const SYNC = 0;
    /**
     * Generated from protobuf enum <code>ASYNC = 1;</code>
     */
    const ASYNC = 1;
}

