<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Response.proto

namespace APIGateway\Protobuf;

if (false) {
    /**
     * This class is deprecated. Use APIGateway\Protobuf\Response\Code instead.
     * @deprecated
     */
    class Response_Code {}
}
class_exists(Response\Code::class);
@trigger_error('APIGateway\Protobuf\Response_Code is deprecated and will be removed in the next major release. Use APIGateway\Protobuf\Response\Code instead', E_USER_DEPRECATED);

