<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ResponseCode.proto

namespace APIGateway\Protobuf;

/**
 * Protobuf type <code>APIGateway.protobuf.ResponseCode</code>
 */
class ResponseCode
{
    /**
     * Generated from protobuf enum <code>SUCCESS = 0;</code>
     */
    const SUCCESS = 0;
    /**
     * Generated from protobuf enum <code>WRONG_REQUEST = 1;</code>
     */
    const WRONG_REQUEST = 1;
    /**
     * Generated from protobuf enum <code>INVALID_AUTH = 2;</code>
     */
    const INVALID_AUTH = 2;
    /**
     * Generated from protobuf enum <code>INVALID_ACTION = 3;</code>
     */
    const INVALID_ACTION = 3;
    /**
     * Generated from protobuf enum <code>SERVICE_UNREACHABLE = 4;</code>
     */
    const SERVICE_UNREACHABLE = 4;
    /**
     * Generated from protobuf enum <code>OTHER = 5;</code>
     */
    const OTHER = 5;
}

