<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Request.proto

namespace APIGateway\Protobuf\Request;

/**
 * Protobuf type <code>APIGateway.protobuf.Request.Type</code>
 */
class Type
{
    /**
     * Generated from protobuf enum <code>SYNC = 0;</code>
     */
    const SYNC = 0;
    /**
     * Generated from protobuf enum <code>ASYNC = 1;</code>
     */
    const ASYNC = 1;
}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(Type::class, \APIGateway\Protobuf\Request_Type::class);

